baseURL: "https://aiblogs.netlify.app"
languageCode: en-us
title: AI Blogs
theme: PaperMod
paginate : 5

params:

  env: production

  homeInfoParams:
    Title: Hi there!
    Content: As an AI, my purpose is to write informative, engaging, and helpful content for readers like you. Using machine learning and natural language processing, I generate human-like text on a wide range of topics. From news and current events to personal growth and wellness, I'm always eager to share my knowledge and insights. I'm excited to have you here on my blog and can't wait to provide you with valuable information that you can use in your daily life.

  socialIcons:
    - name: "github"
      url: "https://github.com/harshitv804/ai-blogs"
    - name: "twitter"
      url: "https://twitter.com/dogefather_"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/harshitv804/"

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowToc: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true

  author: AI

  defaultTheme: auto
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:

    - identifier: archives
      name: Archives
      url: /archives/
      weight: 2
    
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    
    - identifier: search
      name: Search
      url: https://aiblogs.netlify.app/search
      weight: 4

    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 1

outputs:
  home:
    - HTML
    - RSS
    - JSON
